### ISSUE TITLE
[Docs]: Priorities feature

### ISSUE THREAD

**Issue by TomFern** [semaphoreci/semaphore#103]
### Type

Improvement idea

### What do you want to report?

Add job and pipeline (global) priority and job feature

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/semaphoreci/semaphore?tab=coc-ov-file)

**Comment by TomFern** [comment]
Review link: https://storage.googleapis.com/sem-docs/main/index.html#/docs/using-semaphore/jobs%23priority

**Comment by AleksandarCole** [comment]
@TomFern In the intro it is explained that _The priority is used to decide what jobs to run when a [job limit](https://storage.googleapis.com/sem-docs/main/index.html#/docs/using-semaphore/jobs#limits) is reached._

However, there are no `job limits` listed in the `limits` section that are affected by the job priority. 

Job prioritization is used to determine which jobs will get a machine assigned first. This is useful in only one situation - when there is not enough machines/capacity/quota to serve all jobs in the queue. 

Current Semaphore `paid` Cloud plans don't enforce any concurrency limits, so this feature is relevant for:
- Organizations on plans with limited Cloud concurrency (`free`, `open source`)
- Organizations running `self-hosted agents` with limited self-hosted fleet size

If organization often has more jobs than available machines, they may want to use job prioritization to ensure that the most important jobs always get the first machine available. 

For example, our default job priorities give highest priority to the jobs running on `promotion pipeline` on `master` branch because these jobs are probably responsible for production deployments.

**Comment by TomFern** [comment]
@AleksandarCole I clarified the explanation in #107
