### ISSUE TITLE
[Docs]: Explain job parallelism

### ISSUE THREAD

**Issue by TomFern** [semaphoreci/semaphore#107]
### Type

Improvement idea

### What do you want to report?

Explain the `parallelism` parameter in the jobs page

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/semaphoreci/semaphore?tab=coc-ov-file)

**Comment by TomFern** [comment]
Review link: https://storage.googleapis.com/sem-docs/main/index.html#/docs/using-semaphore/jobs%23job-parallelism

**Comment by AleksandarCole** [comment]
@TomFern we are mentioning _test partitioning strategy_ as the reason for using job parallelism, but the job parallelism is not enough to split the tests. User has to use additional tools like [semaphore test booster](https://github.com/renderedtext/test-boosters) or 3rd party tools like Knapsack. 

Otherwise all parallel jobs will run the whole test suite. 

I'm concerned that without clarification users will expect this to split tests out of the box. Maybe we can add additional clarification until we improve this area of the product (test splitting). Wdyt?

**Comment by TomFern** [comment]
@AleksandarCole Fixed on #160
