### ISSUE TITLE
Github status check name changed?

### ISSUE THREAD

**Issue by guoquan** [semaphoreci/semaphore#42]
Hi, I noticed GitHub blocked one of my pull requests because a certain status is not reported by semaphore. I checked the detail and realized that GitHub is expecting "Unit tests", while semaphore reported "ci/semaphoreci/push: Unit tests" success.
"Unit tests" is the block name we have in your semaphore config and it was good. And status are reported in this name at least before my last PR to this repos about 3 days ago.

I suspect did semaphore team has updated the naming rule of the status report to GitHub with some prefix like "ci/semaphoreci/<action>: <block_name>". Is that the case? I think this is good in general but your users should be notified about this. Otherwise would be blocked down just like it happened to me.

**Comment by radwo** [comment]
Hi Guo Quan,

Thanks for the report.

We are currently working on support for tags and pull request. During that process, the names of status checks changed. Current ones are based on the webhooks we receive from GitHub.

Possible prefixes are `ci/semaphoreci/push`, `ci/semaphoreci/tag`, and `ci/semaphoreci/pr`.

In the future, we'll make sure to be more informative when such changes will be introduced.

I am truly sorry for any inconveniences caused by this change.

Kind regards,

**Comment by guoquan** [comment]
A lot of changes have been made to v2.0. I understand those are many efforts have been made to improve v2.0. I hope to like semaphoreci again.
