### ISSUE TITLE
[Docs]: Secrets Page - Review

### ISSUE THREAD

**Issue by AleksandarCole** [semaphoreci/semaphore#48]
### Type

Maintenance task

### What do you want to report?

Help us by reviewing the Secrets page:
https://storage.googleapis.com/sem-docs/main/index.html#/docs/using-semaphore/secrets

Read the [Review Guide](https://github.com/semaphoreci/semaphore/blob/main/docs/docs-contributing/REVIEWING.md) to get more information on what to focus on when reviewing the documentation pages. 

Use the following checklist to ensure you've covered all the steps:

- [ ] The page is clear and comprehensible
- [ ] No information is missing
- [ ] All examples and code snippets have been tested and are working
- [ ] Language and formatting match the [Style Guide](https://github.com/semaphoreci/semaphore/blob/main/docs/docs-contributing/STYLE_GUIDE.md)
- [ ] There are no broken links and page is properly segmented and easy to navigate
- [ ] Final report has been submitted in this issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by csidyel** [comment]
PR https://github.com/semaphoreci/semaphore/pull/194

### Inaccurate information
![image](https://github.com/user-attachments/assets/2253fb7a-c2b7-44ed-88eb-6e6cca9fe091)

Fixed in the PR. Available in Startup.

### Broken links:

- [jobs](https://storage.googleapis.com/sem-docs/main/index.html#/jobs#secrets)
- [Organization](https://storage.googleapis.com/sem-docs/main/index.html#/organizations)
- [Project](https://storage.googleapis.com/sem-docs/main/index.html#/projects)
- [Environment credentials](https://storage.googleapis.com/sem-docs/main/index.html#/promotions#credentials)
- [deployment targets (environments)](https://storage.googleapis.com/sem-docs/main/index.html#/promotions#deployment-targets)
- [projects](https://storage.googleapis.com/sem-docs/main/index.html#/projects)
- [credentials in environments](https://storage.googleapis.com/sem-docs/main/index.html#/promotions#credentials)
- [organization settings](https://storage.googleapis.com/sem-docs/main/index.html#/organizations#general-settings)
- [debug session](https://storage.googleapis.com/sem-docs/main/index.html#/jobs#debug-jobs)
- [attaching to a running job](https://storage.googleapis.com/sem-docs/main/index.html#/jobs#attach-job)
- [project](https://storage.googleapis.com/sem-docs/main/index.html#/projects)
- [promotions and environments](https://storage.googleapis.com/sem-docs/main/index.html#/promotions#credentials)

**Comment by mateuscap** [comment]
Overall structure and contents:
- [ ] Sections _Deployment Targets credentials_ and _Private repositories and dependencies_ are not related to the main theme

Missing info:
- [ ]  How to create a secret from a YAML file: `sem create -f path-to-yaml/yaml-name.yml`

Needs clarification:
- [ ] Currently, for security reasons, `sem get secret <secret-name>` does not show the secret contents(`env_var` values  or file content)

Improvement suggestion:
- [ ] Add secret YAML example, i.e, OR links to Secrets YAML page
```
apiVersion: v1alpha
kind: Secret
metadata:
  name: secret_name
org_config:
  debug_access: JOB_DEBUG_NO
  attach_access: JOB_ATTACH_NO
data:
  env_vars:
    - name: EnvVar1
      value: value1
  files:
  - path: file.txt
    content: SGVsbG8sIFNlbWFwaG9yZSE=

```
