### ISSUE TITLE
Semaphore Allow job to fail

### ISSUE THREAD

**Issue by Baklap4** [semaphoreci/semaphore#68]
Heey, is it possible to say a pipeline succeeds while one of the listed blocks is failing?

Within gitlab ci we can define `allow_failure` on a job: https://docs.gitlab.com/ee/ci/yaml/#allow_failure

The issue we're having is that our macos builds are not reliable in their timings. But we don't want to wait for 1 hour to stop a job so we've used max_execution_time to decrease the time.

Another solution for us would be able to 'skip' a block

**Comment by Baklap4** [comment]
I couldn't find such an option. @Ivana-Markovic do you perhaps have a solution for this 'problem'?

**Comment by csidyel** [comment]
@Baklap4 You can [skip blocks](https://docs.semaphoreci.com/reference/pipeline-yaml-reference/#skip-in-blocks) using the [when condition](https://docs.semaphoreci.com/reference/conditions-reference/).

**Comment by Baklap4** [comment]
Aight this is exactly what we needed thanks :)!

**Comment by FranklinYu** [comment]
We have another scenario for allowed failure: we have a matrix of products, but we’d like to provide tier-1 and tier-2 support to different products, so the tier-2 failure should generate warning instead of failing the entire workflow. (Think of the Rust compiler providing tiered support for different platforms.) Is this currently possible?
